# Generated by Django 3.0.7 on 2020-06-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corso',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
