# Generated by Django 3.0.7 on 2020-06-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_corso_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='foto',
            field=models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to=''),
        ),
    ]
