# Generated by Django 3.0.7 on 2020-06-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20200610_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='posti_rimanenti',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
