# Generated by Django 3.0.7 on 2020-06-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20200608_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
