# Generated by Django 3.0.7 on 2020-06-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_auto_20200610_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='corso',
            name='posti_rimanenti',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
