# Generated by Django 3.0.7 on 2020-06-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_scheda_autore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Giorno della prenotazione', verbose_name='Giorno della prenotazione')),
                ('start_time', models.TimeField(help_text='Ora di inizio', verbose_name='Ora di inizio')),
                ('end_time', models.TimeField(help_text='Ora di fine', verbose_name='Ora di fine')),
                ('notes', models.TextField(blank=True, help_text='Inserisci il tuo nome e le motivazioni', null=True, verbose_name='Inserisci il tuo nome e le motivazioni')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
    ]
