# Generated by Django 3.0.7 on 2020-06-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_prenotazione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prenotazione',
            options={},
        ),
    ]
