# Generated by Django 3.0.7 on 2020-06-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_auto_20200612_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenotazione',
            name='day',
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='notes',
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
