# Generated by Django 3.0.7 on 2020-06-12 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0015_prenotazione_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.Cliente'),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.Pt'),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
