# Generated by Django 3.0.7 on 2020-06-12 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0017_auto_20200612_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 21, 24, 43)),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 21, 24, 43)),
        ),
    ]
