# Generated by Django 3.0.7 on 2020-06-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0018_auto_20200612_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
