# Generated by Django 3.0.7 on 2020-06-13 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0019_auto_20200612_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenotazione',
            name='description',
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='title',
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 13)),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
